# Generated by Django 5.1.3 on 2024-11-14 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pets',
            options={},
        ),
    ]
