# Generated by Django 5.1.3 on 2024-11-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pets_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='name',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
